@MinimalApi_HostAddress = http://localhost:5266

POST {{MinimalApi_HostAddress}}/usuarios
Content-Type: application/json

{
  "nome": "Jose",
  "login": "jose"
}

###

GET {{MinimalApi_HostAddress}}/usuarios
Accept: application/json

###

GET {{MinimalApi_HostAddress}}/dragoes
Accept: application/json

###

POST {{MinimalApi_HostAddress}}/dragoes
Content-Type: application/json

{
  "nome": "Toothless",
  "imagemUrl": "https://placehold.co/600x400?text=Toothless"
}

###

GET {{MinimalApi_HostAddress}}/quiz/pergunta
Accept: application/json

###

POST {{MinimalApi_HostAddress}}/quiz/responder
Content-Type: application/json

{
  "usuarioId": 1,
  "dragaoId": 1,
  "respostaInformada": "Smaug",
  "tempoRespostaSegundos": 4
}

###

GET {{MinimalApi_HostAddress}}/quiz/ranking
Accept: application/json
