// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalApi.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MinimalApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MinimalApi.Models.Dragao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.ToTable("Dragoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagemUrl = "https://placehold.co/600x400?text=Smaug",
                            Nome = "Smaug"
                        },
                        new
                        {
                            Id = 2,
                            ImagemUrl = "https://placehold.co/600x400?text=Drogon",
                            Nome = "Drogon"
                        },
                        new
                        {
                            Id = 3,
                            ImagemUrl = "https://placehold.co/600x400?text=Falkor",
                            Nome = "Falkor"
                        });
                });

            modelBuilder.Entity("MinimalApi.Models.QuizTentativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Acertou")
                        .HasColumnType("boolean");

                    b.Property<int>("DragaoId")
                        .HasColumnType("integer");

                    b.Property<int>("PontosGanhos")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RespondidaEmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RespostaInformada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TempoRespostaSegundos")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DragaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("QuizTentativas");
                });

            modelBuilder.Entity("MinimalApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("PontuacaoTotal")
                        .HasColumnType("integer");

                    b.Property<int>("TotalAcertos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MinimalApi.Models.QuizTentativa", b =>
                {
                    b.HasOne("MinimalApi.Models.Dragao", "Dragao")
                        .WithMany("Tentativas")
                        .HasForeignKey("DragaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinimalApi.Models.Usuario", "Usuario")
                        .WithMany("Tentativas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dragao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MinimalApi.Models.Dragao", b =>
                {
                    b.Navigation("Tentativas");
                });

            modelBuilder.Entity("MinimalApi.Models.Usuario", b =>
                {
                    b.Navigation("Tentativas");
                });
#pragma warning restore 612, 618
        }
    }
}
